import {
  AlertTriangle,
  BookOpen,
  Briefcase,
  Calendar,
  Globe,
  TrendingUp,
} from "lucide-react";

export const newsArticles: NewsArticle[] = [
  {
    id: "1",
    title: "Chính phủ công bố gói hỗ trợ 10.000 tỷ đồng cho nông nghiệp 2024",
    excerpt:
      "Thủ tướng Chính phủ vừa ký quyết định phê duyệt gói hỗ trợ tín dụng ưu đãi 10.000 tỷ đồng nhằm thúc đẩy phát triển nông nghiệp bền vững.",
    content: "",
    author: "Ban Biên tập",
    publishedAt: "2024-01-20",
    category: "Chính sách",
    image: "/placeholder.svg?height=300&width=500",
    views: 5420,
    featured: true,
    urgent: true,
    tags: ["Chính sách", "Hỗ trợ", "Tín dụng", "Nông nghiệp"],
    source: "Bộ Nông nghiệp và Phát triển Nông thôn",
  },
  {
    id: "2",
    title: "Cảnh báo dịch bệnh cúm gia cầm H5N1 tại các tỉnh phía Bắc",
    excerpt:
      "Cục Thú y khuyến cáo các tỉnh phía Bắc tăng cường biện pháp phòng chống dịch bệnh cúm gia cầm H5N1 sau khi phát hiện ổ dịch mới.",
    content: "",
    author: "Phòng Tin tức",
    publishedAt: "2024-01-18",
    category: "Cảnh báo",
    image: "/placeholder.svg?height=300&width=500",
    views: 3210,
    featured: true,
    urgent: true,
    tags: ["Dịch bệnh", "Gia cầm", "Cảnh báo", "Phòng chống"],
    source: "Cục Thú y",
  },
  {
    id: "3",
    title: "Giá lúa gạo xuất khẩu tăng mạnh trong quý I/2024",
    excerpt:
      "Theo báo cáo của Hiệp hội Lương thực Việt Nam, giá lúa gạo xuất khẩu đã tăng 15% so với cùng kỳ năm trước nhờ nhu cầu thế giới tăng cao.",
    content: "",
    author: "Bộ phận Thị trường",
    publishedAt: "2024-01-16",
    category: "Thị trường",
    image: "/placeholder.svg?height=300&width=500",
    views: 2890,
    featured: false,
    urgent: false,
    tags: ["Xuất khẩu", "Lúa gạo", "Giá cả", "Thị trường"],
    source: "Hiệp hội Lương thực Việt Nam",
  },
  {
    id: "4",
    title: "Nghiên cứu mới: Giống lúa ST25 kháng hạn được công nhận quốc tế",
    excerpt:
      "Viện Cây lương thực và Cây thực phẩm vừa công bố thành công trong việc phát triển giống lúa ST25 có khả năng kháng hạn cao.",
    content: "",
    author: "Ban Khoa học",
    publishedAt: "2024-01-14",
    category: "Nghiên cứu",
    image: "/placeholder.svg?height=300&width=500",
    views: 1750,
    featured: false,
    urgent: false,
    tags: ["Nghiên cứu", "Giống lúa", "Kháng hạn", "ST25"],
    source: "Viện Cây lương thực và Cây thực phẩm",
  },
  {
    id: "5",
    title: "Dự báo thời tiết: Đợt rét đậm kéo dài đến cuối tháng 1",
    excerpt:
      "Trung tâm Dự báo Khí tượng Thủy văn Quốc gia cảnh báo đợt rét đậm, rét hại sẽ kéo dài đến cuối tháng 1, ảnh hưởng đến sản xuất nông nghiệp.",
    content: "",
    author: "Phòng Thời tiết",
    publishedAt: "2024-01-12",
    category: "Thời tiết",
    image: "/placeholder.svg?height=300&width=500",
    views: 4320,
    featured: true,
    urgent: false,
    tags: ["Thời tiết", "Rét đậm", "Dự báo", "Nông nghiệp"],
    source: "Trung tâm Dự báo Khí tượng Thủy văn Quốc gia",
  },
  {
    id: "6",
    title: "Hội nghị quốc tế về nông nghiệp bền vững sẽ diễn ra tại Hà Nội",
    excerpt:
      "Hội nghị quốc tế về nông nghiệp bền vững và an ninh lương thực sẽ được tổ chức tại Hà Nội từ ngày 15-17/2/2024.",
    content: "",
    author: "Ban Tổ chức",
    publishedAt: "2024-01-10",
    category: "Sự kiện",
    image: "/placeholder.svg?height=300&width=500",
    views: 1420,
    featured: false,
    urgent: false,
    tags: ["Hội nghị", "Quốc tế", "Bền vững", "An ninh lương thực"],
    source: "Bộ Nông nghiệp và Phát triển Nông thôn",
  },
  {
    id: "7",
    title: "Chương trình đào tạo nông dân ứng dụng công nghệ 4.0",
    excerpt:
      "Bộ Nông nghiệp và Phát triển Nông thôn phối hợp với các trường đại học triển khai chương trình đào tạo nông dân về công nghệ 4.0.",
    content: "",
    author: "Phòng Đào tạo",
    publishedAt: "2024-01-08",
    category: "Đào tạo",
    image: "/placeholder.svg?height=300&width=500",
    views: 980,
    featured: false,
    urgent: false,
    tags: ["Đào tạo", "Công nghệ 4.0", "Nông dân", "Ứng dụng"],
    source: "Bộ Nông nghiệp và Phát triển Nông thôn",
  },
  {
    id: "8",
    title: "Thị trường nông sản hữu cơ Việt Nam tăng trưởng 25% năm 2023",
    excerpt:
      "Báo cáo thống kê cho thấy thị trường nông sản hữu cơ Việt Nam đạt mức tăng trưởng 25% trong năm 2023, vượt xa kỳ vọng.",
    content: "",
    author: "Phòng Thống kê",
    publishedAt: "2024-01-05",
    category: "Thị trường",
    image: "/placeholder.svg?height=300&width=500",
    views: 2150,
    featured: false,
    urgent: false,
    tags: ["Hữu cơ", "Thống kê", "Tăng trưởng", "Thị trường"],
    source: "Tổng cục Thống kê",
  },
];

export const newsCategories = [
  { name: "Tất cả", value: "all", icon: Globe },
  { name: "Chính sách", value: "Chính sách", icon: Briefcase },
  { name: "Thị trường", value: "Thị trường", icon: TrendingUp },
  { name: "Cảnh báo", value: "Cảnh báo", icon: AlertTriangle },
  { name: "Nghiên cứu", value: "Nghiên cứu", icon: BookOpen },
  { name: "Thời tiết", value: "Thời tiết", icon: Globe },
  { name: "Sự kiện", value: "Sự kiện", icon: Calendar },
  { name: "Đào tạo", value: "Đào tạo", icon: BookOpen },
];
